version: '3'
services:

## Routers
  router1:
    image: mongo
    container_name: router-01
    command: mongos --port 27017 --configdb rs-config/config1:27017,config2:27017,config3:27017 --bind_ip_all
    volumes:
      - scripts:/scripts
      - data:/data
    ports:
      - 27117:27017
  router2:
    image: mongo
    container_name: router-02
    command: mongos --port 27017 --configdb rs-config/config1:27017,config2:27017,config3:27017 --bind_ip_all
    volumes:
      - scripts:/scripts
      - data:/data
    ports:
      - 27118:27017

## Config Servers
  config1:
    image: mongo
    container_name: config-01 
    command: mongod --port 27017 --configsvr --replSet rs-config
    volumes:
      - scripts:/scripts
    ports:
      - 27119:27017
  config2:
    image: mongo
    container_name: config-02 
    command: mongod --port 27017 --configsvr --replSet rs-config
    volumes:
      - scripts:/scripts
    ports:
      - 27120:27017
  config3:
    image: mongo
    container_name: config-03 
    command: mongod --port 27017 --configsvr --replSet rs-config
    volumes:
      - scripts:/scripts
    ports:
      - 27121:27017

## Shards
  ## Shards 1
   
  shard1-1:
    image: mongo
    container_name: shard1-1
    command: mongod --port 27017 --shardsvr --replSet rs-shard-1
    volumes:
      - scripts:/scripts
    ports:
      - 27122:27017
  shard1-2:
    image: mongo
    container_name: shard1-2
    command: mongod --port 27017 --shardsvr --replSet rs-shard-1
    volumes:
      - scripts:/scripts
    ports:
      - 27123:27017
  shard1-3:
    image: mongo
    container_name: shard1-3
    command: mongod --port 27017 --shardsvr --replSet rs-shard-1
    volumes:
      - scripts:/scripts
    ports:
      - 27124:27017

  ## Shards 02
  shard2-1:
    image: mongo
    container_name: shard2-1
    command: mongod --port 27017 --shardsvr --replSet rs-shard-2
    volumes:
      - scripts:/scripts
    ports:
      - 27125:27017
  shard2-2:
    image: mongo
    container_name: shard2-2
    command: mongod --port 27017 --shardsvr --replSet rs-shard-2
    volumes:
      - scripts:/scripts
    ports:
      - 27126:27017
  shard2-3:
    image: mongo
    container_name: shard2-3
    command: mongod --port 27017 --shardsvr --replSet rs-shard-2
    volumes:
      - scripts:/scripts
    ports:
      - 27127:27017

  ## Shards 3
  shard3-1:
    image: mongo
    container_name: shard3-1
    command: mongod --port 27017 --shardsvr --replSet rs-shard-3
    volumes:
      - scripts:/scripts
    ports:
      - 27128:27017
  shard3-2:
    image: mongo
    container_name: shard3-2
    command: mongod --port 27017 --shardsvr --replSet rs-shard-3
    volumes:
      - scripts:/scripts
    ports:
      - 27129:27017
  shard3-3:
    image: mongo
    container_name: shard3-3
    command: mongod --port 27017 --shardsvr --replSet rs-shard-3
    volumes:
      - scripts:/scripts
    ports:
      - 27130:27017
volumes:
  scripts:
    driver: local
    driver_opts:
      type: none
      device: ./scripts
      o: bind
  data:
    driver: local
    driver_opts:
      type: none
      device: ./data
      o: bind
